apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    environment: debug
---
apiVersion: v1
kind: Namespace
metadata:
  name: kong
---