apiVersion: v1
kind: Service
metadata:
  name: notifications
  namespace: app
spec:
  selector:
    app: notifications-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---