apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: kafka-pv-1
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: /mnt/data/kafka1
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: manual